/**
 * Token Ledger - Institutional Seed Dataset
 * Company: Meridian Capital Group / Meridian Capital Markets Ltd
 * Primary Infrastructure: Solana, Coinbase, Kraken, Securitize, Backed, CIMB
 * Reporting Period: August 2026 Close
 */

import {
  OrganizationSettings,
  LegalEntity,
  UserProfile,
  DataSource,
  NormalizedTransaction,
  ReconciliationBreakItem,
  ChartAccount,
  AccountingRule,
  JournalEntry,
  AssetValuation,
  MonthEndTask,
  AuditEvent,
  FiveWayReconciliationRecord,
} from './types';

export const INITIAL_USER: UserProfile = {
  id: 'usr_sarah_lim',
  name: 'Sarah Lim, CPA',
  email: 'sarah.lim@meridiancap.com',
  role: 'CONTROLLER',
  title: 'Financial Controller & Digital Asset Operations Lead',
};

export const MOCK_USERS: UserProfile[] = [
  INITIAL_USER,
  {
    id: 'usr_james_tan',
    name: 'James Tan, CA',
    email: 'james.tan@meridiancap.com',
    role: 'ACCOUNTANT',
    title: 'Senior Tokenized Asset Accountant',
  },
  {
    id: 'usr_david_ross',
    name: 'David Ross, CFA',
    email: 'david.ross@meridiancap.com',
    role: 'CFO',
    title: 'Chief Financial Officer',
  },
  {
    id: 'usr_elena_vance',
    name: 'Elena Vance, CISA',
    email: 'elena.vance@kpmg-audit.com',
    role: 'AUDITOR',
    title: 'Lead External IT & Financial Auditor',
  },
  {
    id: 'usr_alex_chen',
    name: 'Alex Chen',
    email: 'alex.chen@meridiancap.com',
    role: 'TREASURY',
    title: 'Digital Treasury Operations Manager',
  },
];

export const INITIAL_ORGANIZATION: OrganizationSettings = {
  id: 'org_meridian_capital',
  name: 'Meridian Capital Group',
  reportingCurrency: 'USD',
  framework: 'IFRS',
  costBasisMethod: 'FIFO',
  periodCloseDate: '2026-08-31',
  materialityThresholdUsd: 50.0,
  materialityPercent: 0.05,
  makerCheckerEnabled: true,
  activePeriod: 'August 2026',
};

export const INITIAL_ENTITIES: LegalEntity[] = [
  { id: 'ent_group', code: 'GRP', name: 'Meridian Capital Group (Consolidated)', jurisdiction: 'Global', isDefault: true },
  { id: 'ent_markets', code: 'MCM', name: 'Meridian Capital Markets Ltd', jurisdiction: 'United Kingdom / ADGM' },
  { id: 'ent_asset_mgmt', code: 'MAM', name: 'Meridian Asset Management Pte Ltd', jurisdiction: 'Singapore' },
  { id: 'ent_treasury_spv', code: 'MTSPV', name: 'Meridian Tokenized Treasury SPV', jurisdiction: 'Cayman Islands' },
];

export const INITIAL_DATA_SOURCES: DataSource[] = [
  // 1. Blockchain / DLT
  {
    id: 'src_solana_treasury',
    entityId: 'ent_markets',
    name: 'Meridian Tokenized Asset Treasury',
    category: 'BLOCKCHAIN',
    type: 'WALLET',
    provider: 'SOLANA',
    addressOrAccount: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
    purpose: 'Tokenized asset custody and settlement (Solana Treasury Account for bNVDA & SOL)',
    status: 'CONNECTED',
    lastSyncAt: '2 minutes ago',
    txCount: 126,
    assetCount: 2,
    healthStatus: 'HEALTHY',
    promoted: true,
    network: 'Solana Mainnet-Beta',
    balanceEstimateUsd: 3967490,
    isReadOnly: true,
  },

  // 1b. Issuer-Operated Digital Wallets (Asset Custody by Chain)
  {
    id: 'src_blackrock_wallet_sol',
    entityId: 'ent_markets',
    name: 'BlackRock Digital Wallet — Solana',
    category: 'BLOCKCHAIN',
    type: 'WALLET',
    provider: 'SOLANA',
    addressOrAccount: 'BR9xLmQ2Wk8pT4vNzD7fXsBUIDL1solWallet92Qp',
    purpose: 'BlackRock USD Institutional Digital Liquidity Fund (BUIDL) custody on Solana',
    status: 'CONNECTED',
    lastSyncAt: '3 minutes ago',
    txCount: 21,
    assetCount: 1,
    healthStatus: 'HEALTHY',
    network: 'Solana Mainnet-Beta',
    balanceEstimateUsd: 3000000,
    isReadOnly: true,
    walletName: 'BlackRock Digital Wallet',
    custodian: 'BNY Mellon (BNY)',
  },
  {
    id: 'src_blackrock_wallet_eth',
    entityId: 'ent_markets',
    name: 'BlackRock Digital Wallet — Ethereum',
    category: 'BLOCKCHAIN',
    type: 'WALLET',
    provider: 'ETHEREUM',
    addressOrAccount: '0xBR4a1c7E9fD2b6A8c3D5e0F1a2B3c4D5e6F7BUID',
    purpose: 'BlackRock USD Institutional Digital Liquidity Fund (BUIDL) custody on Ethereum',
    status: 'CONNECTED',
    lastSyncAt: '4 minutes ago',
    txCount: 15,
    assetCount: 1,
    healthStatus: 'HEALTHY',
    network: 'Ethereum Mainnet',
    balanceEstimateUsd: 2000000,
    isReadOnly: true,
    walletName: 'BlackRock Digital Wallet',
    custodian: 'BNY Mellon (BNY)',
  },
  {
    id: 'src_khazanah_wallet_sol',
    entityId: 'ent_markets',
    name: 'Khazanah Digital Wallet — Solana',
    category: 'BLOCKCHAIN',
    type: 'WALLET',
    provider: 'SOLANA',
    addressOrAccount: 'KZ7pQ1sVkXwSUKUKsolWallet2830SkAxTreasu9',
    purpose: 'Khazanah Sovereign Tokenized Sukuk custody on Solana',
    status: 'CONNECTED',
    lastSyncAt: '5 minutes ago',
    txCount: 9,
    assetCount: 1,
    healthStatus: 'HEALTHY',
    network: 'Solana Mainnet-Beta',
    balanceEstimateUsd: 560000,
    isReadOnly: true,
    walletName: 'Khazanah Digital Wallet',
    custodian: 'Cokeeps',
  },
  {
    id: 'src_khazanah_wallet_eth',
    entityId: 'ent_markets',
    name: 'Khazanah Digital Wallet — Ethereum',
    category: 'BLOCKCHAIN',
    type: 'WALLET',
    provider: 'ETHEREUM',
    addressOrAccount: '0xKZ2b8d4E1fA6c9D3e5F7a8B9c0D1e2F3a4B5SUK',
    purpose: 'Khazanah Sovereign Tokenized Sukuk custody on Ethereum',
    status: 'CONNECTED',
    lastSyncAt: '6 minutes ago',
    txCount: 5,
    assetCount: 1,
    healthStatus: 'HEALTHY',
    network: 'Ethereum Mainnet',
    balanceEstimateUsd: 336000,
    isReadOnly: true,
    walletName: 'Khazanah Digital Wallet',
    custodian: 'Cokeeps',
  },
  {
    id: 'src_khazanah_wallet_vsys',
    entityId: 'ent_markets',
    name: 'Khazanah Digital Wallet — VSystem',
    category: 'BLOCKCHAIN',
    type: 'WALLET',
    provider: 'VSYSTEM',
    addressOrAccount: 'VSYS-KZ-SUKUK-DEPOSIT-77213',
    purpose: 'Khazanah Sovereign Tokenized Sukuk custody on VSystem',
    status: 'CONNECTED',
    lastSyncAt: '7 minutes ago',
    txCount: 3,
    assetCount: 1,
    healthStatus: 'HEALTHY',
    network: 'VSystem Mainnet',
    balanceEstimateUsd: 224000,
    isReadOnly: true,
    walletName: 'Khazanah Digital Wallet',
    custodian: 'Cokeeps',
  },
  {
    id: 'src_cimb_wallet_sol',
    entityId: 'ent_markets',
    name: 'CIMB Digital Wallet — Solana',
    category: 'BLOCKCHAIN',
    type: 'WALLET',
    provider: 'SOLANA',
    addressOrAccount: 'CIMBsolWalletDEP883019284solTrsy77',
    purpose: 'CIMB Institutional Tokenized Deposit custody on Solana',
    status: 'CONNECTED',
    lastSyncAt: '6 minutes ago',
    txCount: 11,
    assetCount: 1,
    healthStatus: 'HEALTHY',
    network: 'Solana Mainnet-Beta',
    balanceEstimateUsd: 672000,
    isReadOnly: true,
    walletName: 'CIMB Digital Wallet',
    custodian: 'Gambit Custody',
  },
  {
    id: 'src_cimb_wallet_eth',
    entityId: 'ent_markets',
    name: 'CIMB Digital Wallet — Ethereum',
    category: 'BLOCKCHAIN',
    type: 'WALLET',
    provider: 'ETHEREUM',
    addressOrAccount: '0xCIMB3d5E7f9A1b2C4d6E8f0A2b4C6d8E0f2CIMB',
    purpose: 'CIMB Institutional Tokenized Deposit custody on Ethereum',
    status: 'CONNECTED',
    lastSyncAt: '8 minutes ago',
    txCount: 8,
    assetCount: 1,
    healthStatus: 'HEALTHY',
    network: 'Ethereum Mainnet',
    balanceEstimateUsd: 448000,
    isReadOnly: true,
    walletName: 'CIMB Digital Wallet',
    custodian: 'Gambit Custody',
  },

  // 2. Exchange / Custody Sources
  {
    id: 'src_coinbase_institutional',
    entityId: 'ent_markets',
    name: 'Meridian Coinbase Institutional Account',
    category: 'EXCHANGE',
    type: 'EXCHANGE',
    provider: 'COINBASE',
    addressOrAccount: 'ACT-CB-INST-9820-MERIDIAN',
    purpose: 'Institutional execution and fiat off-ramp (no tokenized asset custody held here)',
    status: 'CONNECTED',
    lastSyncAt: '5 minutes ago',
    txCount: 48,
    assetCount: 0,
    healthStatus: 'HEALTHY',
    balanceEstimateUsd: 500000,
    isReadOnly: true,
  },
  {
    id: 'src_kraken_institutional',
    entityId: 'ent_asset_mgmt',
    name: 'Meridian Kraken Institutional Account',
    category: 'EXCHANGE',
    type: 'EXCHANGE',
    provider: 'KRAKEN',
    addressOrAccount: 'KRAK-MERIDIAN-ASSET-MGMT-01',
    purpose: 'Tokenized asset execution and custody (bNVDA)',
    status: 'WARNING',
    lastSyncAt: '8 minutes ago',
    txCount: 37,
    assetCount: 1,
    healthStatus: 'EXCEPTION',
    reconciliationExceptionCount: 1,
    balanceEstimateUsd: 1156500,
    isReadOnly: true,
  },

  // 3. Tokenization Platforms
  {
    id: 'src_securitize_feed',
    entityId: 'ent_markets',
    name: 'Securitize BUIDL Platform Feed',
    category: 'TOKENIZATION_PLATFORM',
    type: 'TOKENIZATION_PLATFORM',
    provider: 'SECURITIZE',
    addressOrAccount: 'REG-SEC-BUIDL-MERIDIAN-881',
    purpose: 'BUIDL primary issuance cap-table synchronization & monthly dividend feed',
    status: 'CONNECTED',
    lastSyncAt: '12 minutes ago',
    txCount: 14,
    assetCount: 1,
    healthStatus: 'HEALTHY',
    balanceEstimateUsd: 5000000,
    isReadOnly: true,
  },
  {
    id: 'src_backed_feed',
    entityId: 'ent_asset_mgmt',
    name: 'Backed Finance Tokenized Equity Platform Feed',
    category: 'TOKENIZATION_PLATFORM',
    type: 'TOKENIZATION_PLATFORM',
    provider: 'BACKED',
    addressOrAccount: 'REG-BACKED-BNVDA-9102',
    purpose: 'Backed NVDA (bNVDA) tokenization collateral verification & Swiss custodian attestation',
    status: 'CONNECTED',
    lastSyncAt: '15 minutes ago',
    txCount: 8,
    assetCount: 1,
    healthStatus: 'HEALTHY',
    balanceEstimateUsd: 1285000,
    isReadOnly: true,
  },
  {
    id: 'src_custom_tokenization',
    entityId: 'ent_treasury_spv',
    name: 'Custom Sovereign Tokenization Platform',
    category: 'TOKENIZATION_PLATFORM',
    type: 'TOKENIZATION_PLATFORM',
    provider: 'CUSTOM_TOKENIZATION',
    addressOrAccount: 'PLATFORM-SOVEREIGN-SUKUK-01',
    purpose: 'Institutional Sukuk smart issuance lifecycle and coupon distribution ledger',
    status: 'CONNECTED',
    lastSyncAt: '20 minutes ago',
    txCount: 6,
    assetCount: 1,
    healthStatus: 'HEALTHY',
    balanceEstimateUsd: 1120000,
    isReadOnly: true,
  },

  // 4. Banking / Settlement
  {
    id: 'src_bank_settlement',
    entityId: 'ent_markets',
    name: 'Institutional Bank Settlement Account (Standard Chartered)',
    category: 'BANKING',
    type: 'BANK',
    provider: 'ERP',
    addressOrAccount: 'SCB-USD-OPERATING-0912',
    purpose: 'USD treasury clearing and fiat subscription/redemption account',
    status: 'CONNECTED',
    lastSyncAt: '1 hour ago',
    txCount: 32,
    assetCount: 1,
    healthStatus: 'HEALTHY',
    balanceEstimateUsd: 6500000,
    isReadOnly: true,
  },

  // 5. Internal Systems
  {
    id: 'src_erp_gl',
    entityId: 'ent_group',
    name: 'Meridian General Ledger (SAP ERP)',
    category: 'INTERNAL_SYSTEMS',
    type: 'ERP',
    provider: 'ERP',
    addressOrAccount: 'SAP-S4HANA-CO-MERIDIAN-GL',
    purpose: 'Enterprise master chart of accounts, journal batch ingestion & financial reporting',
    status: 'CONNECTED',
    lastSyncAt: '10 minutes ago',
    txCount: 88,
    healthStatus: 'HEALTHY',
    isReadOnly: false,
  },
  {
    id: 'src_tms_internal',
    entityId: 'ent_group',
    name: 'Treasury Management System (TMS)',
    category: 'INTERNAL_SYSTEMS',
    type: 'ERP',
    provider: 'ERP',
    addressOrAccount: 'TMS-KYRIBA-MERIDIAN-CORP',
    purpose: 'Intraday cash positioning, liquidity forecasting & limits control',
    status: 'CONNECTED',
    lastSyncAt: '30 minutes ago',
    txCount: 42,
    healthStatus: 'HEALTHY',
    isReadOnly: true,
  },

  // 6. Manual Sources
  {
    id: 'src_custodian_stmt',
    entityId: 'ent_markets',
    name: 'Custodian Monthly Statement (PDF/CSV)',
    category: 'MANUAL',
    type: 'CSV',
    provider: 'CSV',
    addressOrAccount: 'STATEMENT-MAERKI-BAUMANN-AUG2026.CSV',
    purpose: 'Independent Swiss third-party custodian statement for Backed NVDA shares',
    status: 'CONNECTED',
    lastSyncAt: '1 day ago',
    txCount: 4,
    healthStatus: 'HEALTHY',
    isReadOnly: true,
  },
];

export const INITIAL_CHART_OF_ACCOUNTS: ChartAccount[] = [
  // Assets (1000-1999)
  { code: '1100', name: 'Cash & Cash Equivalents (USD Settlement Account)', category: 'ASSET', normalBalance: 'DEBIT', balance: 6500000, description: 'Bank balances and fiat clearing accounts', active: true },
  { code: '1150', name: 'Tokenized Cash & Bank Deposits (CIMB Deposit)', category: 'ASSET', normalBalance: 'DEBIT', balance: 1120000, description: 'Institutional wholesale tokenized deposit cash leg (MYR 5,000,000)', active: true, isDigitalAssetAccount: true, supportedAssetSymbol: 'CIMB-DEP' },
  { code: '1200', name: 'Tokenized Assets — Master Control Subledger', category: 'ASSET', normalBalance: 'DEBIT', balance: 30785000, description: 'Subledger master control for all tokenized assets', active: true, isDigitalAssetAccount: true },
  { code: '1210', name: 'Tokenized Funds — BlackRock BUIDL', category: 'ASSET', normalBalance: 'DEBIT', balance: 5000000, description: 'BlackRock USD Institutional Digital Liquidity Fund (5,000,000 units)', active: true, isDigitalAssetAccount: true, supportedAssetSymbol: 'BUIDL' },
  { code: '1220', name: 'Tokenized Securities — Khazanah Sovereign Sukuk', category: 'ASSET', normalBalance: 'DEBIT', balance: 1120000, description: 'Sovereign Tokenized Sukuk bond investment at amortized cost', active: true, isDigitalAssetAccount: true, supportedAssetSymbol: 'SKUK' },
  { code: '1230', name: 'Tokenized Equity — Backed NVIDIA (bNVDA)', category: 'ASSET', normalBalance: 'DEBIT', balance: 1285000, description: 'Backed NVDA tokenized equity (10,000 units @ $128.50 fair value)', active: true, isDigitalAssetAccount: true, supportedAssetSymbol: 'bNVDA' },
  { code: '1240', name: 'Digital Assets — Solana Treasury (SOL)', category: 'ASSET', normalBalance: 'DEBIT', balance: 2844990, description: 'SOL treasury & validator staking holdings at FIFO cost', active: true, isDigitalAssetAccount: true, supportedAssetSymbol: 'SOL' },
  { code: '1250', name: 'Digital Assets — Stablecoins (USDC)', category: 'ASSET', normalBalance: 'DEBIT', balance: 2200000, description: 'USD fiat-pegged settlement stablecoin', active: true, isDigitalAssetAccount: true, supportedAssetSymbol: 'USDC' },
  { code: '1300', name: 'Accrued Tokenized Asset Distribution Receivables', category: 'ASSET', normalBalance: 'DEBIT', balance: 18450, description: 'Accrued monthly yield dividends from BUIDL and Sukuk coupons', active: true },
  
  // Liabilities (2000-2999)
  { code: '2100', name: 'Tokenized Asset Settlement Clearing Payables', category: 'LIABILITY', normalBalance: 'CREDIT', balance: 0, description: 'Interim clearing for in-transit DLT trades', active: true },
  { code: '2200', name: 'Accrued Tokenization Platform & Custody Fees', category: 'LIABILITY', normalBalance: 'CREDIT', balance: 5400, description: 'Platform fees due to Securitize / Backed / Custodians', active: true },

  // Equity (3000-3999)
  { code: '3100', name: 'Retained Earnings', category: 'EQUITY', normalBalance: 'CREDIT', balance: 16025750, description: 'Cumulative historical earnings (balances the subledger: Total Assets = Total Liabilities + Equity + current-period Net Income)', active: true },
  { code: '3200', name: 'Tokenized Asset Revaluation Reserve (FVOCI / Net Income)', category: 'EQUITY', normalBalance: 'CREDIT', balance: 3450000, description: 'Unrealized fair value gains under IFRS 9 / IAS 38', active: true },

  // Income (4000-4999)
  { code: '4100', name: 'Realized Gains on Tokenized Asset Disposals', category: 'INCOME', normalBalance: 'CREDIT', balance: 412000, description: 'Net recognized gain from tokenized securities and equity sales', active: true },
  { code: '4200', name: 'Tokenized Fund Dividend & Sukuk Profit Income', category: 'INCOME', normalBalance: 'CREDIT', balance: 184500, description: 'Yield distributions from BlackRock BUIDL and Khazanah Sukuk', active: true },
  { code: '4300', name: 'Validator Staking & Other Operating Income', category: 'INCOME', normalBalance: 'CREDIT', balance: 42100, description: 'Solana validator consensus yield and rent exemption reclaims', active: true },

  // Expenses (5000-5999)
  { code: '5100', name: 'Realized Losses on Tokenized Asset Disposals', category: 'EXPENSE', normalBalance: 'DEBIT', balance: 18200, description: 'Realized loss on digital asset disposals', active: true },
  { code: '5200', name: 'Network & DLT Protocol Settlement Fees', category: 'EXPENSE', normalBalance: 'DEBIT', balance: 410, description: 'Solana and DLT transaction network fees consumed', active: true },
  { code: '5300', name: 'Tokenization Platform, Registry & Custody Fees', category: 'EXPENSE', normalBalance: 'DEBIT', balance: 8500, description: 'Issuer platform fees and safeguarding charges', active: true },
  { code: '5400', name: 'Exchange Execution & Brokerage Fees', category: 'EXPENSE', normalBalance: 'DEBIT', balance: 4200, description: 'Coinbase and Kraken execution commissions', active: true },
];

export const INITIAL_ACCOUNTING_RULES: AccountingRule[] = [
  {
    id: 'rule_buidl_internal_transfer',
    name: 'Cross-Chain Internal Transfer (No Disposal)',
    conditionDescription: 'IF Sender = BlackRock Digital Wallet AND Receiver = BlackRock Digital Wallet (e.g. Ethereum -> Solana chain)',
    txTypeMatch: 'INTERNAL_TRANSFER',
    debitAccountCode: '1210',
    debitAccountName: 'Tokenized Funds — BlackRock BUIDL (Solana Chain)',
    creditAccountCode: '1210',
    creditAccountName: 'Tokenized Funds — BlackRock BUIDL (Ethereum Chain)',
    isPnLRecognized: false,
    explanationTemplate: 'Internal cross-chain movement within the same issuer-custodied wallet. No economic disposal or realized gain/loss recognized.',
    active: true,
    autoAppliedCount: 64,
  },
  {
    id: 'rule_sukuk_settlement',
    name: 'Tokenized Sukuk Purchase via Tokenized Deposit',
    conditionDescription: 'IF TxType = Purchase AND Asset = SKUK AND SettlementLeg = CIMB Tokenized Deposit',
    txTypeMatch: 'PURCHASE',
    assetMatch: 'SKUK',
    debitAccountCode: '1220',
    debitAccountName: 'Tokenized Securities — Khazanah Sovereign Sukuk',
    creditAccountCode: '1150',
    creditAccountName: 'Tokenized Cash & Bank Deposits (CIMB Deposit)',
    isPnLRecognized: false,
    explanationTemplate: 'Sovereign Sukuk asset capitalized at nominal settlement; CIMB tokenized deposit clearing credited.',
    active: true,
    autoAppliedCount: 12,
  },
  {
    id: 'rule_buidl_dividend',
    name: 'Securitize BUIDL Monthly Dividend Distribution',
    conditionDescription: 'IF Source = Securitize Platform Feed AND TxType = Distribution',
    txTypeMatch: 'DISTRIBUTION',
    assetMatch: 'BUIDL',
    debitAccountCode: '1100',
    debitAccountName: 'Cash & Cash Equivalents (USD Settlement Account)',
    creditAccountCode: '4200',
    creditAccountName: 'Tokenized Fund Dividend & Sukuk Profit Income',
    isPnLRecognized: true,
    explanationTemplate: 'Recognized as Operating Dividend Revenue in Cash clearing account upon issuer distribution.',
    active: true,
    autoAppliedCount: 28,
  },
  {
    id: 'rule_solana_network_fee',
    name: 'Solana DLT Protocol Network Fee',
    conditionDescription: 'IF Network Fee > 0',
    txTypeMatch: 'NETWORK_FEE',
    debitAccountCode: '5200',
    debitAccountName: 'Network & DLT Protocol Settlement Fees',
    creditAccountCode: '1240',
    creditAccountName: 'Digital Assets — Solana Treasury (SOL)',
    isPnLRecognized: true,
    explanationTemplate: 'Directly expensed as an operating DLT transaction network fee.',
    active: true,
    autoAppliedCount: 126,
  },
];

export const INITIAL_ASSET_VALUATIONS: AssetValuation[] = [
  // 1. BlackRock BUIDL
  {
    id: 'asset_buidl',
    assetSymbol: 'BUIDL',
    name: 'BlackRock USD Institutional Digital Liquidity Fund',
    assetType: 'TOKENIZED_FUND',
    network: 'Multi-Chain (Solana & Ethereum)',
    isinOrCusip: 'US09257V1008',
    issuer: 'BlackRock Financial Management / Securitize',
    underlyingAsset: 'US Treasury Bills, Repo Agreements & Cash Equivalents',
    walletName: 'BlackRock Digital Wallet',
    custodian: 'BNY Mellon (BNY)',
    chains: ['Solana', 'Ethereum'],
    isSimulatedDemoNetwork: false,
    totalQuantity: 5000000.0,
    quantity: 5000000.0,
    spotPriceUsd: 1.00,
    currentPriceUsd: 1.00,
    marketValueUsd: 5000000.0,
    costBasisUsd: 5000000.0,
    unrealizedGainLossUsd: 0.0,
    unrealizedGainLossPercent: 0.0,
    priceSource: 'Securitize Issuer NAV & BNY Mellon Attestation ($1.00 Par)',
    lastPriceTimestamp: '2026-08-31 23:59:00 UTC',
    change24hPercent: 0.0,
    valuationLevel: 'Level 1 Observable Net Asset Value',
    positionsByLocation: [
      {
        id: 'loc_buidl_sol',
        assetSymbol: 'BUIDL',
        locationName: 'BlackRock Digital Wallet (Solana)',
        locationType: 'ISSUER_WALLET',
        provider: 'Solana',
        chain: 'Solana',
        custodian: 'BNY Mellon (BNY)',
        walletOrAccount: 'BR9xLmQ2Wk8pT4vNzD7fXsBUIDL1solWallet92Qp',
        legalEntity: 'Meridian Capital Markets Ltd',
        quantity: 3000000.0,
        carryingValueUsd: 3000000.0,
        fairValueUsd: 3000000.0,
        currency: 'USD',
        lastVerified: '3 minutes ago',
        reconciliationStatus: 'RECONCILED',
      },
      {
        id: 'loc_buidl_eth',
        assetSymbol: 'BUIDL',
        locationName: 'BlackRock Digital Wallet (Ethereum)',
        locationType: 'ISSUER_WALLET',
        provider: 'Ethereum',
        chain: 'Ethereum',
        custodian: 'BNY Mellon (BNY)',
        walletOrAccount: '0xBR4a1c7E9fD2b6A8c3D5e0F1a2B3c4D5e6F7BUID',
        legalEntity: 'Meridian Capital Markets Ltd',
        quantity: 2000000.0,
        carryingValueUsd: 2000000.0,
        fairValueUsd: 2000000.0,
        currency: 'USD',
        lastVerified: '4 minutes ago',
        reconciliationStatus: 'RECONCILED',
      },
    ],
  },

  // 2. Khazanah Tokenized Sukuk
  {
    id: 'asset_sukuk',
    assetSymbol: 'SKUK',
    name: 'Khazanah Sovereign Tokenized Sukuk (Ijarah)',
    assetType: 'TOKENIZED_SECURITY',
    network: 'Solana (Demo Subledger)',
    isinOrCusip: 'MYB102930219',
    issuer: 'Khazanah Nasional Berhad (Sovereign Wealth Fund)',
    underlyingAsset: 'Sovereign Physical Infrastructure Assets & Leasehold',
    walletName: 'Khazanah Digital Wallet',
    custodian: 'Cokeeps',
    chains: ['Solana', 'Ethereum', 'VSystem'],
    isSimulatedDemoNetwork: true,
    demoNetworkNote: 'Simulated Demo Infrastructure: Operating on Solana demo subledger; real-world issuance retains independent sovereign DLT metadata.',
    totalQuantity: 2000.0,
    quantity: 2000.0,
    nominalValue: 5000000.0,
    spotPriceUsd: 560.00,
    currentPriceUsd: 560.00,
    marketValueUsd: 1120000.0,
    costBasisUsd: 1120000.0,
    unrealizedGainLossUsd: 0.0,
    unrealizedGainLossPercent: 0.0,
    priceSource: 'Bursa Malaysia Bond Pricing Agency (BPAM) / CIMB Valuation',
    lastPriceTimestamp: '2026-08-31 23:59:00 UTC',
    change24hPercent: 0.1,
    valuationLevel: 'Level 2 Observable Yield Matrix',
    positionsByLocation: [
      {
        id: 'loc_sukuk_sol',
        assetSymbol: 'SKUK',
        locationName: 'Khazanah Digital Wallet (Solana)',
        locationType: 'ISSUER_WALLET',
        provider: 'Solana',
        chain: 'Solana',
        custodian: 'Cokeeps',
        walletOrAccount: 'KZ7pQ1sVkXwSUKUKsolWallet2830SkAxTreasu9',
        legalEntity: 'Meridian Capital Markets Ltd',
        quantity: 1000.0,
        nominalValue: 2500000.0,
        carryingValueUsd: 560000.0,
        fairValueUsd: 560000.0,
        currency: 'MYR / USD Equiv',
        lastVerified: '3 minutes ago',
        reconciliationStatus: 'RECONCILED',
      },
      {
        id: 'loc_sukuk_eth',
        assetSymbol: 'SKUK',
        locationName: 'Khazanah Digital Wallet (Ethereum)',
        locationType: 'ISSUER_WALLET',
        provider: 'Ethereum',
        chain: 'Ethereum',
        custodian: 'Cokeeps',
        walletOrAccount: '0xKZ2b8d4E1fA6c9D3e5F7a8B9c0D1e2F3a4B5SUK',
        legalEntity: 'Meridian Capital Markets Ltd',
        quantity: 600.0,
        nominalValue: 1500000.0,
        carryingValueUsd: 336000.0,
        fairValueUsd: 336000.0,
        currency: 'MYR / USD Equiv',
        lastVerified: '4 minutes ago',
        reconciliationStatus: 'RECONCILED',
      },
      {
        id: 'loc_sukuk_vsys',
        assetSymbol: 'SKUK',
        locationName: 'Khazanah Digital Wallet (VSystem)',
        locationType: 'ISSUER_WALLET',
        provider: 'VSystem',
        chain: 'VSystem',
        custodian: 'Cokeeps',
        walletOrAccount: 'VSYS-KZ-SUKUK-DEPOSIT-77213',
        legalEntity: 'Meridian Capital Markets Ltd',
        quantity: 400.0,
        nominalValue: 1000000.0,
        carryingValueUsd: 224000.0,
        fairValueUsd: 224000.0,
        currency: 'MYR / USD Equiv',
        lastVerified: '5 minutes ago',
        reconciliationStatus: 'RECONCILED',
      },
    ],
  },

  // 3. CIMB Tokenized Deposit
  {
    id: 'asset_cimb_dep',
    assetSymbol: 'CIMB-DEP',
    name: 'CIMB Institutional Tokenized Deposit (Settlement Leg)',
    assetType: 'TOKENIZED_DEPOSIT',
    network: 'Multi-Chain (Solana & Ethereum)',
    isinOrCusip: 'CIMB-DEP-883019284',
    issuer: 'CIMB Bank Berhad (Wholesale Banking)',
    underlyingAsset: 'Institutional Central Bank Reserves & Commercial Cash Deposit',
    walletName: 'CIMB Digital Wallet',
    custodian: 'Gambit Custody',
    chains: ['Solana', 'Ethereum'],
    isSimulatedDemoNetwork: false,
    totalQuantity: 5000000.0,
    quantity: 5000000.0,
    spotPriceUsd: 0.224,
    currentPriceUsd: 0.224,
    marketValueUsd: 1120000.0,
    costBasisUsd: 1120000.0,
    unrealizedGainLossUsd: 0.0,
    unrealizedGainLossPercent: 0.0,
    priceSource: 'CIMB Wholesale Institutional Par FX Rate (USD/MYR 4.464)',
    lastPriceTimestamp: '2026-08-31 23:59:00 UTC',
    change24hPercent: 0.0,
    valuationLevel: 'Level 1 Cash Equivalent',
    positionsByLocation: [
      {
        id: 'loc_cimb_sol',
        assetSymbol: 'CIMB-DEP',
        locationName: 'CIMB Digital Wallet (Solana)',
        locationType: 'ISSUER_WALLET',
        provider: 'Solana',
        chain: 'Solana',
        custodian: 'Gambit Custody',
        walletOrAccount: 'CIMBsolWalletDEP883019284solTrsy77',
        legalEntity: 'Meridian Capital Markets Ltd',
        quantity: 3000000.0,
        nominalValue: 3000000.0,
        carryingValueUsd: 672000.0,
        fairValueUsd: 672000.0,
        currency: 'MYR / USD Equiv',
        lastVerified: '6 minutes ago',
        reconciliationStatus: 'RECONCILED',
      },
      {
        id: 'loc_cimb_eth',
        assetSymbol: 'CIMB-DEP',
        locationName: 'CIMB Digital Wallet (Ethereum)',
        locationType: 'ISSUER_WALLET',
        provider: 'Ethereum',
        chain: 'Ethereum',
        custodian: 'Gambit Custody',
        walletOrAccount: '0xCIMB3d5E7f9A1b2C4d6E8f0A2b4C6d8E0f2CIMB',
        legalEntity: 'Meridian Capital Markets Ltd',
        quantity: 2000000.0,
        nominalValue: 2000000.0,
        carryingValueUsd: 448000.0,
        fairValueUsd: 448000.0,
        currency: 'MYR / USD Equiv',
        lastVerified: '8 minutes ago',
        reconciliationStatus: 'RECONCILED',
      },
    ],
  },

  // 4. NVIDIA Tokenized Equity — Backed (bNVDA) with 50-Unit Exception
  {
    id: 'asset_bnvda',
    assetSymbol: 'bNVDA',
    name: 'Backed NVDA Tokenized Equity (bNVDA)',
    assetType: 'TOKENIZED_EQUITY',
    network: 'Kraken & Solana Treasury',
    isinOrCusip: 'CH1173294265',
    issuer: 'Backed Finance AG (Swiss DLT Tokenization Framework)',
    underlyingAsset: '1:1 Fully Collateralized NVIDIA Corp Common Shares at Maerki Baumann & Co',
    isSimulatedDemoNetwork: true,
    demoNetworkNote: 'Simulated Demo Infrastructure: Operating on Solana demo subledger; real-world issuance retains independent sovereign DLT metadata.',
    totalQuantity: 10000.0,
    quantity: 9950.0, // 50 units in transit break
    spotPriceUsd: 128.50,
    currentPriceUsd: 128.50,
    marketValueUsd: 1278575.0, // 9950 * 128.50
    costBasisUsd: 1150000.0,
    unrealizedGainLossUsd: 128575.0,
    unrealizedGainLossPercent: 11.18,
    priceSource: 'NASDAQ Composite & Pyth Real-Time Institutional Equity Feed',
    lastPriceTimestamp: '2026-08-31 23:59:00 UTC',
    change24hPercent: 2.4,
    valuationLevel: 'Level 1 Quoted Underlying Stock',
    positionsByLocation: [
      {
        id: 'loc_bnvda_krk',
        assetSymbol: 'bNVDA',
        locationName: 'Meridian Kraken Institutional Account',
        locationType: 'KRAKEN_ACCOUNT',
        provider: 'Kraken',
        walletOrAccount: 'KRAK-MERIDIAN-ASSET-MGMT-01',
        legalEntity: 'Meridian Asset Management Pte Ltd',
        quantity: 9000.0,
        carryingValueUsd: 1035000.0,
        fairValueUsd: 1156500.0,
        currency: 'USD',
        lastVerified: '8 minutes ago',
        reconciliationStatus: 'RECONCILED',
      },
      {
        id: 'loc_bnvda_sol',
        assetSymbol: 'bNVDA',
        locationName: 'Meridian Tokenized Asset Treasury (Solana)',
        locationType: 'SOLANA_WALLET',
        provider: 'Solana',
        walletOrAccount: '7xKX...82Qp',
        legalEntity: 'Meridian Capital Markets Ltd',
        quantity: 950.0,
        carryingValueUsd: 109250.0,
        fairValueUsd: 122075.0,
        currency: 'USD',
        lastVerified: '2 minutes ago',
        reconciliationStatus: 'BREAK',
        notes: '⚠ 50-Unit variance detected: Kraken recorded 1,000 transferred; Solana received 950 units.',
      },
    ],
  },

  // 5. Solana Operational Gas & Staking
  {
    id: 'asset_sol',
    assetSymbol: 'SOL',
    name: 'Solana (Treasury Reserve & Operational Gas)',
    assetType: 'CRYPTOCURRENCY',
    network: 'Solana Mainnet-Beta',
    totalQuantity: 18450.0,
    quantity: 18450.0,
    spotPriceUsd: 154.20,
    currentPriceUsd: 154.20,
    marketValueUsd: 2844990.0,
    costBasisUsd: 2214000.0,
    unrealizedGainLossUsd: 630990.0,
    unrealizedGainLossPercent: 28.5,
    priceSource: 'Institutional Pyth / Chainlink Composite VWAP',
    lastPriceTimestamp: '2026-08-31 23:59:00 UTC',
    change24hPercent: 4.2,
    valuationLevel: 'Level 1 Quoted',
    positionsByLocation: [
      {
        id: 'loc_sol_treasury',
        assetSymbol: 'SOL',
        locationName: 'Meridian Tokenized Asset Treasury',
        locationType: 'SOLANA_WALLET',
        provider: 'Solana',
        walletOrAccount: '7xKX...82Qp',
        legalEntity: 'Meridian Capital Markets Ltd',
        quantity: 18450.0,
        carryingValueUsd: 2214000.0,
        fairValueUsd: 2844990.0,
        currency: 'USD',
        lastVerified: '2 minutes ago',
        reconciliationStatus: 'RECONCILED',
      },
    ],
  },
];

export const INITIAL_FIVE_WAY_RECONCILIATION: FiveWayReconciliationRecord[] = [
  // 1. BlackRock BUIDL
  {
    id: 'five_way_buidl',
    assetSymbol: 'BUIDL',
    assetName: 'BlackRock USD Institutional Digital Liquidity Fund',
    assetType: 'TOKENIZED_FUND',
    solanaDltUnits: 3000000,
    solanaDltVerified: true,
    solanaDltSource: 'BlackRock Digital Wallet — Solana (BNY Mellon Custody)',
    solanaDltRef: 'Slot #28841029 / Token Account BUIDL-SOL-882',
    exchangeUnits: 2000000,
    exchangeBreakdown: 'BlackRock Digital Wallet — Ethereum: 2,000,000 (BNY Mellon Custody)',
    exchangeVerified: true,
    exchangeSource: 'BlackRock Digital Wallet Ethereum On-Chain Feed',
    exchangeRef: '0xBR4a1c7E9fD2b6A8c3D5e0F1a2B3c4D5e6F7BUID',
    issuerPlatformUnits: 5000000,
    issuerPlatformVerified: true,
    issuerPlatformSource: 'Securitize Cap Table API',
    issuerPlatformRef: 'REG-SEC-BUIDL-MERIDIAN-881',
    subledgerUnits: 5000000,
    subledgerVerified: true,
    subledgerRef: 'Token Ledger Asset Subledger #1210',
    generalLedgerValueUsd: 5000000,
    generalLedgerUnits: 5000000,
    generalLedgerVerified: true,
    generalLedgerAccount: '1210 Tokenized Funds — BlackRock BUIDL',
    totalCalculatedUnits: 5000000,
    varianceUnits: 0,
    varianceUsd: 0,
    status: 'RECONCILED',
    lastVerifiedTimestamp: '2026-08-31 23:59:00 UTC',
  },

  // 2. Khazanah Tokenized Sukuk
  {
    id: 'five_way_sukuk',
    assetSymbol: 'SKUK',
    assetName: 'Khazanah Sovereign Tokenized Sukuk',
    assetType: 'TOKENIZED_SECURITY',
    solanaDltUnits: 1000,
    solanaDltVerified: true,
    solanaDltSource: 'Khazanah Digital Wallet — Solana (Cokeeps Custody)',
    solanaDltRef: 'DLT Account SUKUK-MY-091 / Block #28840112',
    exchangeUnits: 1000,
    exchangeBreakdown: 'Khazanah Digital Wallet — Ethereum: 600 | VSystem: 400 (Cokeeps Custody)',
    exchangeVerified: true,
    exchangeSource: 'Khazanah Digital Wallet Ethereum & VSystem On-Chain Feeds',
    exchangeRef: '0xKZ2b8d4E1fA6c9D3e5F7a8B9c0D1e2F3a4B5SUK / VSYS-KZ-SUKUK-DEPOSIT-77213',
    issuerPlatformUnits: 2000,
    issuerPlatformVerified: true,
    issuerPlatformSource: 'Sovereign Tokenization Platform',
    issuerPlatformRef: 'PLATFORM-SOVEREIGN-SUKUK-01',
    subledgerUnits: 2000,
    subledgerVerified: true,
    subledgerRef: 'Token Ledger Asset Subledger #1220',
    generalLedgerValueUsd: 1120000,
    generalLedgerUnits: 2000,
    generalLedgerVerified: true,
    generalLedgerAccount: '1220 Tokenized Securities — Khazanah Sukuk',
    totalCalculatedUnits: 2000,
    varianceUnits: 0,
    varianceUsd: 0,
    status: 'RECONCILED',
    lastVerifiedTimestamp: '2026-08-31 23:55:00 UTC',
  },

  // 3. CIMB Tokenized Deposit
  {
    id: 'five_way_cimb_dep',
    assetSymbol: 'CIMB-DEP',
    assetName: 'CIMB Institutional Tokenized Deposit',
    assetType: 'TOKENIZED_DEPOSIT',
    solanaDltUnits: 3000000,
    solanaDltVerified: true,
    solanaDltSource: 'CIMB Digital Wallet — Solana (Gambit Custody)',
    solanaDltRef: 'CIMBsolWalletDEP883019284solTrsy77',
    exchangeUnits: 2000000,
    exchangeBreakdown: 'CIMB Digital Wallet — Ethereum: 2,000,000 (Gambit Custody)',
    exchangeVerified: true,
    exchangeSource: 'CIMB Digital Wallet Ethereum On-Chain Feed',
    exchangeRef: '0xCIMB3d5E7f9A1b2C4d6E8f0A2b4C6d8E0f2CIMB',
    issuerPlatformUnits: 5000000,
    issuerPlatformVerified: true,
    issuerPlatformSource: 'CIMB Institutional Core Banking / Token Issuance Ledger',
    issuerPlatformRef: 'DEP-CIMB-MERIDIAN-RM5M',
    subledgerUnits: 5000000,
    subledgerVerified: true,
    subledgerRef: 'Token Ledger Cash Subledger #1150',
    generalLedgerValueUsd: 1120000,
    generalLedgerUnits: 5000000,
    generalLedgerVerified: true,
    generalLedgerAccount: '1150 Tokenized Cash & Bank Deposits',
    totalCalculatedUnits: 5000000,
    varianceUnits: 0,
    varianceUsd: 0,
    status: 'RECONCILED',
    lastVerifiedTimestamp: '2026-08-31 23:58:00 UTC',
  },

  // 4. NVIDIA Tokenized Equity — Backed (bNVDA) with 50-Unit Exception
  {
    id: 'five_way_bnvda',
    assetSymbol: 'bNVDA',
    assetName: 'Backed NVDA Tokenized Equity (bNVDA)',
    assetType: 'TOKENIZED_EQUITY',
    solanaDltUnits: 950,
    solanaDltVerified: true,
    solanaDltSource: 'Solana Treasury (7xKX...82Qp)',
    solanaDltRef: 'Slot #28841090 / Token Account bNVDA-SOL-01',
    exchangeUnits: 9000,
    exchangeBreakdown: 'Kraken: 9,000 units (1,000 withdrawal dispatched)',
    exchangeVerified: true,
    exchangeSource: 'Kraken Institutional API',
    exchangeRef: 'KRAK-WD-BNVDA-1000',
    issuerPlatformUnits: 10000,
    issuerPlatformVerified: true,
    issuerPlatformSource: 'Backed Finance Swiss Registry',
    issuerPlatformRef: 'REG-BACKED-BNVDA-9102',
    subledgerUnits: 10000,
    subledgerVerified: false,
    subledgerRef: 'Token Ledger Asset Subledger #1230',
    generalLedgerValueUsd: 1285000,
    generalLedgerUnits: 10000,
    generalLedgerVerified: false,
    generalLedgerAccount: '1230 Tokenized Equity — Backed NVIDIA',
    totalCalculatedUnits: 9950,
    varianceUnits: -50,
    varianceUsd: -6425.00,
    status: 'EXCEPTION',
    exceptionReason: 'Kraken records indicate that 1,000 tokenized NVIDIA units were transferred to the Meridian Solana Treasury account, while the current Solana position reflects only 950 units associated with the transfer.',
    aiExplanation: 'Kraken records indicate that 1,000 tokenized NVIDIA units were transferred to the Meridian Solana Treasury account, while the current Solana position reflects only 950 units associated with the transfer. Review whether the difference represents settlement timing, an unmatched transaction or an incorrect position record.',
    lastVerifiedTimestamp: '2026-08-31 23:50:00 UTC',
  },
];

export const INITIAL_TRANSACTIONS: NormalizedTransaction[] = [
  // 1. Cross-Chain Internal Transfer: BlackRock Digital Wallet Ethereum -> Solana (500k units BUIDL)
  {
    id: 'tx_buidl_transfer_001',
    externalTxId: 'TX-INT-BUIDL-20260831-01',
    sourceId: 'src_blackrock_wallet_eth',
    sourceName: 'BlackRock Digital Wallet — Ethereum',
    sourceType: 'WALLET',
    network: 'Solana / Ethereum (BlackRock Digital Wallet)',
    walletAccount: '0xBR4a1c7E9fD2b6A8c3D5e0F1a2B3c4D5e6F7BUID',
    walletName: 'BlackRock Digital Wallet',
    custodian: 'BNY Mellon (BNY)',
    entityId: 'ent_markets',
    entityName: 'Meridian Capital Markets Ltd',
    timestamp: '2026-08-31 16:30:00 UTC',
    businessDescription: 'Internal Cross-Chain Transfer of 500,000 BUIDL from Ethereum to Solana (BlackRock Digital Wallet)',
    txType: 'INTERNAL_TRANSFER',
    isInternalTransfer: true,
    economicOwnershipUnchanged: true,
    fromLocation: 'BlackRock Digital Wallet (Ethereum)',
    toLocation: 'BlackRock Digital Wallet (Solana)',
    fromSource: 'BlackRock Digital Wallet — Ethereum',
    toSource: 'BlackRock Digital Wallet — Solana',
    assetSent: 'BUIDL',
    quantitySent: 500000,
    assetReceived: 'BUIDL',
    quantityReceived: 500000,
    feeAsset: 'USDC',
    feeQuantity: 2.50,
    feeFiatValue: 2.50,
    counterparty: 'BlackRock Digital Wallet — Solana (BNY Mellon Custody)',
    fiatValue: 500000.00,
    valuationCurrency: 'USD',
    priceSource: 'Securitize Issuer Par ($1.00)',
    classification: 'INTERNAL_TRANSFER',
    autoClassified: true,
    classificationConfidence: 99,
    classificationRuleReason: 'Applied Rule: Cross-Chain Internal Transfer (No Disposal).',
    debitAccountCode: '1210',
    debitAccountName: 'Tokenized Funds — BlackRock BUIDL (Solana Chain)',
    creditAccountCode: '1210',
    creditAccountName: 'Tokenized Funds — BlackRock BUIDL (Ethereum Chain)',
    costBasis: 500000.00,
    realizedGainLoss: 0.00,
    reconciliationStatus: 'RECONCILED',
    reconciliationMatchMethod: 'CROSS_SOURCE_MATCH',
    sourceRecordMatched: true,
    destinationRecordMatched: true,
    quantityMatched: true,
    timestampMatched: true,
    noDisposalRecognized: true,
    reconciliationNote: 'Matched BlackRock Digital Wallet Ethereum withdrawal #BR-ETH-WD-500K with Solana receipt #BR-SOL-RC-500K. Same BNY Mellon-custodied wallet; ownership unchanged.',
    accountingStatus: 'POSTED',
    approvalStatus: 'APPROVED',
    preparedBy: 'James Tan, CA',
    approverName: 'Sarah Lim, CPA',
    approvedAt: '2026-08-31 17:00:00 UTC',
    txHash: '5xPQ8...99Km (Solana Block #28841029)',
    dltTxReference: '5xPQ8kL99Km22...99Km',
    solanaSignature: '5xPQ8kL99Km22ZpW87T...82Qp',
    movements: [
      { id: 'mov_1', asset: 'BUIDL', quantity: 500000, direction: 'OUT', fiatValue: 500000, walletAddress: '0xBR4a1c7E9fD2b6A8c3D5e0F1a2B3c4D5e6F7BUID' },
      { id: 'mov_2', asset: 'BUIDL', quantity: 500000, direction: 'IN', fiatValue: 500000, walletAddress: 'BR9xLmQ2Wk8pT4vNzD7fXsBUIDL1solWallet92Qp' },
    ],
    rawSourceRecord: { venue: 'BlackRock Digital Wallet — Ethereum', type: 'On-Chain Transfer', amount: 500000, fee: 2.50, status: 'Completed' },
    rawDestinationRecord: { network: 'Solana', type: 'Tokenized Asset Transfer', amount: 500000, feeLamports: 5000, status: 'Finalized' },
    createdAt: '2026-08-31 16:35:00 UTC',
    updatedAt: '2026-08-31 17:00:00 UTC',
  },

  // 2. Tokenized Sukuk Purchase settled via CIMB Tokenized Deposit
  {
    id: 'tx_sukuk_purchase_001',
    externalTxId: 'TX-SUKUK-PURCHASE-20260830-01',
    sourceId: 'src_khazanah_wallet_sol',
    sourceName: 'Khazanah Digital Wallet — Solana',
    sourceType: 'WALLET',
    network: 'Solana Mainnet-Beta (Demo Subledger)',
    walletAccount: 'KZ7pQ1sVkXwSUKUKsolWallet2830SkAxTreasu9',
    walletName: 'Khazanah Digital Wallet',
    custodian: 'Cokeeps',
    entityId: 'ent_markets',
    entityName: 'Meridian Capital Markets Ltd',
    timestamp: '2026-08-30 14:00:00 UTC',
    businessDescription: 'Purchase of RM5,000,000 Khazanah Tokenized Sukuk settled via CIMB Tokenized Deposit',
    txType: 'PURCHASE',
    fromLocation: 'CIMB Digital Wallet (Solana)',
    toLocation: 'Khazanah Digital Wallet (Solana)',
    fromSource: 'CIMB Digital Wallet — Solana',
    toSource: 'Khazanah Digital Wallet — Solana',
    assetReceived: 'SKUK',
    quantityReceived: 2000,
    feeAsset: 'SOL',
    feeQuantity: 0.00005,
    feeFiatValue: 0.0077,
    counterparty: 'Khazanah Nasional Berhad (Cokeeps Custody) / CIMB Wholesale (Gambit Custody)',
    fiatValue: 1120000.00,
    valuationCurrency: 'USD',
    priceSource: 'Bursa Malaysia BPAM / CIMB Institutional Pricing (RM5,000,000 @ 4.464 USD/MYR)',
    classification: 'PURCHASE',
    autoClassified: true,
    classificationConfidence: 98,
    classificationRuleReason: 'Applied Rule: Tokenized Sukuk Purchase via Tokenized Deposit.',
    debitAccountCode: '1220',
    debitAccountName: 'Tokenized Securities — Khazanah Sovereign Sukuk',
    creditAccountCode: '1150',
    creditAccountName: 'Tokenized Cash & Bank Deposits (CIMB Deposit)',
    costBasis: 1120000.00,
    reconciliationStatus: 'RECONCILED',
    reconciliationMatchMethod: 'CROSS_SOURCE_MATCH',
    sourceRecordMatched: true,
    destinationRecordMatched: true,
    quantityMatched: true,
    timestampMatched: true,
    reconciliationNote: 'Fully matched against CIMB Digital Wallet (Solana) settlement debit RM5,000,000, credited into Khazanah Digital Wallet (Solana).',
    accountingStatus: 'POSTED',
    approvalStatus: 'APPROVED',
    preparedBy: 'James Tan, CA',
    approverName: 'Sarah Lim, CPA',
    approvedAt: '2026-08-30 15:30:00 UTC',
    txHash: '4xSKUK...88Zq (Solana Block #28840112)',
    dltTxReference: '4xSKUK...88Zq',
    solanaSignature: '4xSKUK88Zq771092841920...JosgAsU',
    movements: [
      { id: 'mov_3', asset: 'CIMB-DEP', quantity: 5000000, direction: 'OUT', fiatValue: 1120000, walletAddress: 'CIMBsolWalletDEP883019284solTrsy77' },
      { id: 'mov_4', asset: 'SKUK', quantity: 2000, direction: 'IN', fiatValue: 1120000, walletAddress: 'KZ7pQ1sVkXwSUKUKsolWallet2830SkAxTreasu9' },
    ],
    createdAt: '2026-08-30 14:05:00 UTC',
    updatedAt: '2026-08-30 15:30:00 UTC',
  },

  // 3. Kraken -> Solana Transfer of NVIDIA Tokenized Equity (bNVDA) - with 50 Unit Break
  {
    id: 'tx_bnvda_transfer_001',
    externalTxId: 'TX-BNVDA-KRK-SOL-20260829-01',
    sourceId: 'src_kraken_institutional',
    sourceName: 'Meridian Kraken Institutional Account',
    sourceType: 'EXCHANGE',
    network: 'Kraken / Solana Treasury',
    walletAccount: 'KRAK-MERIDIAN-ASSET-MGMT-01',
    entityId: 'ent_asset_mgmt',
    entityName: 'Meridian Asset Management Pte Ltd',
    timestamp: '2026-08-29 11:15:00 UTC',
    businessDescription: 'Transfer of 1,000 Backed NVDA (bNVDA) Tokenized Equity from Kraken to Solana Treasury',
    txType: 'INTERNAL_TRANSFER',
    isInternalTransfer: true,
    fromLocation: 'Meridian Kraken Institutional',
    toLocation: 'Meridian Solana Treasury',
    fromSource: 'Kraken',
    toSource: 'Solana',
    assetSent: 'bNVDA',
    quantitySent: 1000,
    assetReceived: 'bNVDA',
    quantityReceived: 950, // 50 units discrepancy
    feeAsset: 'USDC',
    feeQuantity: 5.00,
    feeFiatValue: 5.00,
    counterparty: 'Meridian Tokenized Asset Treasury (7xKX...82Qp)',
    fiatValue: 128500.00,
    valuationCurrency: 'USD',
    priceSource: 'NASDAQ Composite / Backed Index @ $128.50',
    classification: 'INTERNAL_TRANSFER',
    autoClassified: false,
    suggestedClassification: 'INTERNAL_TRANSFER',
    classificationConfidence: 75,
    classificationRuleReason: 'Kraken records indicate that 1,000 tokenized NVIDIA units were transferred to the Meridian Solana Treasury account, while the current Solana position reflects only 950 units associated with the transfer.',
    debitAccountCode: '1230',
    debitAccountName: 'Tokenized Equity — Backed NVIDIA (Solana Treasury)',
    creditAccountCode: '1230',
    creditAccountName: 'Tokenized Equity — Backed NVIDIA (Kraken Account)',
    reconciliationStatus: 'BREAK',
    reconciliationMatchMethod: 'MANUAL',
    sourceRecordMatched: true,
    destinationRecordMatched: false,
    quantityMatched: false,
    timestampMatched: true,
    reconciliationNote: '⚠ Exception: Kraken dispatched 1,000 units; Solana recorded 950 units. 50 units variance under investigation.',
    accountingStatus: 'UNPOSTED',
    approvalStatus: 'NONE',
    preparedBy: 'James Tan, CA',
    txHash: '7xNVDA...9201 (Solana Block #28839010)',
    dltTxReference: '7xNVDA...9201',
    solanaSignature: '7xNVDA9201...JosgAsU',
    movements: [
      { id: 'mov_5', asset: 'bNVDA', quantity: 1000, direction: 'OUT', fiatValue: 128500, walletAddress: 'KRAK-MERIDIAN-ASSET-MGMT-01' },
      { id: 'mov_6', asset: 'bNVDA', quantity: 950, direction: 'IN', fiatValue: 122075, walletAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU' },
    ],
    rawSourceRecord: { venue: 'Kraken Institutional', type: 'Withdrawal', amount: 1000, asset: 'bNVDA', status: 'Dispatched' },
    rawDestinationRecord: { network: 'Solana', type: 'Tokenized Asset Transfer', amount: 950, asset: 'bNVDA', status: 'Confirmed' },
    createdAt: '2026-08-29 11:20:00 UTC',
    updatedAt: '2026-08-31 18:00:00 UTC',
  },

  // 4. Securitize BUIDL Monthly Dividend Distribution
  {
    id: 'tx_buidl_div_001',
    externalTxId: 'TX-BUIDL-DIV-20260828-01',
    sourceId: 'src_securitize_feed',
    sourceName: 'Securitize BUIDL Platform Feed',
    sourceType: 'TOKENIZATION_PLATFORM',
    network: 'Securitize / Coinbase Institutional',
    walletAccount: 'ACT-CB-INST-9820-MERIDIAN',
    entityId: 'ent_markets',
    entityName: 'Meridian Capital Markets Ltd',
    timestamp: '2026-08-28 18:00:00 UTC',
    businessDescription: 'BlackRock BUIDL Monthly Yield Dividend Distribution ($18,450.00)',
    txType: 'DISTRIBUTION',
    fromLocation: 'Securitize Issuer Distribution Vault',
    toLocation: 'Meridian Coinbase Institutional Account',
    fromSource: 'Securitize',
    toSource: 'Coinbase',
    assetReceived: 'USD',
    quantityReceived: 18450.00,
    fiatValue: 18450.00,
    valuationCurrency: 'USD',
    priceSource: 'Securitize Official Dividend Distribution Statement (4.82% Annualized Yield)',
    classification: 'DISTRIBUTION',
    autoClassified: true,
    classificationConfidence: 99,
    classificationRuleReason: 'Applied Rule: Securitize BUIDL Monthly Dividend Distribution.',
    debitAccountCode: '1100',
    debitAccountName: 'Cash & Cash Equivalents (USD Settlement Account)',
    creditAccountCode: '4200',
    creditAccountName: 'Tokenized Fund Dividend & Sukuk Profit Income',
    reconciliationStatus: 'RECONCILED',
    reconciliationMatchMethod: 'EXACT_HASH',
    reconciliationNote: 'Reconciled against Securitize monthly dividend report DIV-BUIDL-AUG2026.',
    accountingStatus: 'PENDING_APPROVAL',
    approvalStatus: 'PENDING_APPROVAL',
    preparedBy: 'James Tan, CA',
    txHash: 'SEC-DIV-20260828-BUIDL-9921',
    dltTxReference: 'SEC-DIV-20260828-BUIDL-9921',
    movements: [
      { id: 'mov_7', asset: 'USD', quantity: 18450, direction: 'IN', fiatValue: 18450, walletAddress: 'ACT-CB-INST-9820-MERIDIAN' },
    ],
    createdAt: '2026-08-28 18:05:00 UTC',
    updatedAt: '2026-08-28 18:05:00 UTC',
  },

  // 5. Solana Epoch 682 Staking Yield (Unclassified exception ready for AI Assistant demo)
  {
    id: 'tx_sol_001',
    externalTxId: 'TX-SOL-STAKE-EPOCH682',
    sourceId: 'src_solana_treasury',
    sourceName: 'Meridian Tokenized Asset Treasury',
    sourceType: 'WALLET',
    network: 'Solana Mainnet-Beta',
    walletAccount: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
    entityId: 'ent_markets',
    entityName: 'Meridian Capital Markets Ltd',
    timestamp: '2026-08-31 21:00:00 UTC',
    businessDescription: 'Epoch 682 Solana Validator Staking Yield Distribution (42.5 SOL)',
    txType: 'STAKING_REWARD',
    fromLocation: 'Solana Validator Delegation Pool',
    toLocation: 'Meridian Solana Treasury',
    fromSource: 'Solana',
    toSource: 'Solana',
    assetReceived: 'SOL',
    quantityReceived: 42.5,
    fiatValue: 6553.50,
    valuationCurrency: 'USD',
    priceSource: 'Pyth Spot VWAP @ 154.20 USD',
    classification: 'UNKNOWN',
    autoClassified: false,
    classificationConfidence: 45,
    suggestedClassification: 'STAKING_REWARD',
    classificationRuleReason: 'Identified periodic incoming SOL from Solana validator vote account. Suggest Account 4300 (Validator Staking Income).',
    debitAccountCode: '1240',
    debitAccountName: 'Digital Assets — Solana Treasury (SOL)',
    creditAccountCode: '4300',
    creditAccountName: 'Validator Staking & Other Operating Income',
    reconciliationStatus: 'BREAK',
    reconciliationMatchMethod: 'TIMESTAMP_AMOUNT',
    reconciliationNote: 'Pending classification and Controller sign-off in August close batch.',
    accountingStatus: 'DRAFT',
    approvalStatus: 'NONE',
    preparedBy: 'James Tan, CA',
    txHash: '9zX1...84Qp (Solana Block #28841920)',
    dltTxReference: '9zX1kL984Qp22109...',
    solanaSignature: '9zX1kL984Qp221098491823...JosgAsU',
    movements: [
      { id: 'mov_8', asset: 'SOL', quantity: 42.5, direction: 'IN', fiatValue: 6553.50, walletAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU' },
    ],
    createdAt: '2026-08-31 21:05:00 UTC',
    updatedAt: '2026-08-31 21:05:00 UTC',
  },

  // 6. Solana Token Account Rent Reclaim
  {
    id: 'tx_sol_rent_001',
    externalTxId: 'TX-SOL-RENT-RECLAIM-01',
    sourceId: 'src_solana_treasury',
    sourceName: 'Meridian Tokenized Asset Treasury',
    sourceType: 'WALLET',
    network: 'Solana Mainnet-Beta',
    walletAccount: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
    entityId: 'ent_markets',
    entityName: 'Meridian Capital Markets Ltd',
    timestamp: '2026-08-31 22:15:00 UTC',
    businessDescription: 'Reclaim of Tokenized Asset Account Rent Exemption Storage (0.002039 SOL)',
    txType: 'RENT_EXEMPTION',
    fromLocation: 'Closed SPL Token Storage Account',
    toLocation: 'Meridian Solana Treasury',
    fromSource: 'Solana',
    toSource: 'Solana',
    assetReceived: 'SOL',
    quantityReceived: 0.002039,
    fiatValue: 0.314,
    valuationCurrency: 'USD',
    priceSource: 'Pyth Spot @ 154.20 USD',
    classification: 'RENT_EXEMPTION',
    autoClassified: true,
    classificationConfidence: 94,
    classificationRuleReason: 'Closed zero-balance token account storage lamports recovered to treasury.',
    debitAccountCode: '1240',
    debitAccountName: 'Digital Assets — Solana Treasury (SOL)',
    creditAccountCode: '4300',
    creditAccountName: 'Validator Staking & Other Operating Income',
    reconciliationStatus: 'RECONCILED',
    reconciliationMatchMethod: 'EXACT_HASH',
    accountingStatus: 'PENDING_APPROVAL',
    approvalStatus: 'PENDING_APPROVAL',
    preparedBy: 'James Tan, CA',
    txHash: '3wRent...88Lp (Solana Block #28841990)',
    dltTxReference: '3wRent...88Lp',
    solanaSignature: '3wRent88Lp091283...JosgAsU',
    movements: [
      { id: 'mov_9', asset: 'SOL', quantity: 0.002039, direction: 'IN', fiatValue: 0.314, walletAddress: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU' },
    ],
    createdAt: '2026-08-31 22:20:00 UTC',
    updatedAt: '2026-08-31 22:20:00 UTC',
  },
];

export const INITIAL_RECONCILIATION_BREAKS: ReconciliationBreakItem[] = [
  // Intentional Demo Break 1: NVIDIA Tokenized Equity (50-Unit Kraken ↔ Solana Difference)
  {
    id: 'rec_break_001',
    asset: 'bNVDA',
    assetName: 'Backed NVDA Tokenized Equity',
    blockchainBalance: 950.0,
    exchangeBalance: 9000.0,
    ledgerBalance: 10000.0,
    difference: 50.0,
    fiatDifferenceUsd: 6425.0,
    isMaterial: true,
    status: 'OPEN',
    breakCategory: 'TRANSFER_TIMING',
    sourceVenue: 'Meridian Kraken Institutional Account',
    destinationVenue: 'Meridian Tokenized Asset Treasury (Solana)',
    expectedAmount: 1000.0,
    receivedAmount: 950.0,
    potentialReason: 'Kraken records indicate that 1,000 tokenized NVIDIA units were transferred to the Meridian Solana Treasury account, while the current Solana position reflects only 950 units associated with the transfer. Review whether the difference represents settlement timing, an unmatched transaction or an incorrect position record.',
    aiDiagnostic: 'Kraken records indicate that 1,000 tokenized NVIDIA units were transferred to the Meridian Solana Treasury account, while the current Solana position reflects only 950 units associated with the transfer. Review whether the difference represents settlement timing, an unmatched transaction or an incorrect position record.',
    owner: 'Sarah Lim, CPA',
    relatedTxIds: ['tx_bnvda_transfer_001'],
    lastUpdated: '2026-08-31 18:00 UTC',
  },

  // Intentional Demo Break 2: Epoch 682 Solana Staking Yield
  {
    id: 'rec_break_002',
    asset: 'SOL',
    assetName: 'Solana Treasury Reserve',
    blockchainBalance: 18450.0,
    ledgerBalance: 18407.5,
    difference: 42.5,
    fiatDifferenceUsd: 6553.50,
    isMaterial: true,
    status: 'INVESTIGATING',
    breakCategory: 'UNMATCHED_TX',
    sourceVenue: 'Solana Mainnet-Beta Validator Delegation',
    destinationVenue: 'Meridian Tokenized Asset Treasury',
    expectedAmount: 42.5,
    receivedAmount: 42.5,
    potentialReason: 'Epoch 682 staking yield (42.5 SOL) is currently unclassified and pending approval in draft state.',
    aiDiagnostic: 'Periodic incoming block validator yield from vote account. Apply automatic rule to credit Account 4300 Operating Staking Income.',
    owner: 'Sarah Lim, CPA',
    relatedTxIds: ['tx_sol_001'],
    lastUpdated: '2026-08-31 21:15 UTC',
  },

  // Resolved Break: BUIDL Parity Across BlackRock Digital Wallet Chains
  {
    id: 'rec_break_003',
    asset: 'BUIDL',
    assetName: 'BlackRock USD Institutional Digital Liquidity Fund',
    blockchainBalance: 3000000.0,
    exchangeBalance: 2000000.0,
    ledgerBalance: 5000000.0,
    difference: 0.0,
    fiatDifferenceUsd: 0.0,
    isMaterial: false,
    status: 'RESOLVED',
    breakCategory: 'POSITION_MISMATCH',
    sourceVenue: 'BlackRock Digital Wallet — Solana (3M) + Ethereum (2M)',
    destinationVenue: 'Token Ledger Master Subledger',
    potentialReason: 'Cross-chain multi-location position verification confirmed across Securitize cap table.',
    aiDiagnostic: 'All 5,000,000 units verified across BlackRock Digital Wallet on Solana and Ethereum, custodied by BNY Mellon, with 0 variance.',
    owner: 'James Tan, CA',
    resolutionNote: 'Reconciled 5,000,000 units total across BlackRock Digital Wallet — Solana (3,000,000) and Ethereum (2,000,000) against Securitize cap table attestation and BNY Mellon custody confirmation.',
    approver: 'Sarah Lim, CPA',
    approvedAt: '2026-08-31 17:30 UTC',
    relatedTxIds: ['tx_buidl_transfer_001'],
    lastUpdated: '2026-08-31 17:30 UTC',
  },

  // Resolved Break: Khazanah Sovereign Sukuk & CIMB Deposit
  {
    id: 'rec_break_004',
    asset: 'SKUK',
    assetName: 'Khazanah Sovereign Tokenized Sukuk',
    blockchainBalance: 2000.0,
    ledgerBalance: 2000.0,
    difference: 0.0,
    fiatDifferenceUsd: 0.0,
    isMaterial: false,
    status: 'APPROVED',
    breakCategory: 'POSITION_MISMATCH',
    sourceVenue: 'Sovereign Tokenization Platform',
    destinationVenue: 'Meridian Tokenized Asset Treasury',
    potentialReason: 'Purchase settlement matched against CIMB Tokenized Deposit cash leg RM5,000,000.',
    aiDiagnostic: 'Capitalized at RM5,000,000 ($1,120,000 USD) with matched CIMB wholesale deposit credit.',
    owner: 'Alex Chen',
    approver: 'Sarah Lim, CPA',
    approvedAt: '2026-08-30 16:00 UTC',
    relatedTxIds: ['tx_sukuk_purchase_001'],
    lastUpdated: '2026-08-30 16:00 UTC',
  },
];

export const INITIAL_JOURNAL_ENTRIES: JournalEntry[] = [
  // 1. Cross-Chain BUIDL Transfer Journal
  {
    id: 'je_2026_00840',
    journalNumber: 'JE-2026-00840',
    date: '2026-08-31',
    entityId: 'ent_markets',
    sourceName: 'BlackRock Digital Wallet (Ethereum & Solana)',
    description: 'Internal Cross-Chain Transfer of 500,000 BUIDL from Ethereum to Solana (BlackRock Digital Wallet)',
    relatedTxId: 'tx_buidl_transfer_001',
    status: 'POSTED',
    totalDebit: 500000.0,
    totalCredit: 500000.0,
    preparedBy: 'James Tan, CA',
    approvedBy: 'Sarah Lim, CPA',
    approvedAt: '2026-08-31 17:00 UTC',
    ruleApplied: 'Cross-Chain Internal Transfer (No Disposal)',
    lines: [
      { id: 'jl_1', accountCode: '1210', accountName: 'Tokenized Funds — BlackRock BUIDL (Solana Chain)', debit: 500000.0, credit: 0, assetSymbol: 'BUIDL', quantity: 500000.0, memo: 'Transfer receipt at BlackRock Digital Wallet — Solana (BNY Mellon Custody)' },
      { id: 'jl_2', accountCode: '1210', accountName: 'Tokenized Funds — BlackRock BUIDL (Ethereum Chain)', debit: 0, credit: 500000.0, assetSymbol: 'BUIDL', quantity: 500000.0, memo: 'Withdrawal dispatch from BlackRock Digital Wallet — Ethereum (BNY Mellon Custody)' },
    ],
    evidenceHash: 'f418...29ba',
  },

  // 2. Sovereign Sukuk Purchase & CIMB Settlement Journal
  {
    id: 'je_2026_00841',
    journalNumber: 'JE-2026-00841',
    date: '2026-08-30',
    entityId: 'ent_markets',
    sourceName: 'Meridian Solana Treasury & CIMB Settlement',
    description: 'Purchase of RM5,000,000 Khazanah Tokenized Sukuk settled via CIMB Tokenized Deposit',
    relatedTxId: 'tx_sukuk_purchase_001',
    status: 'POSTED',
    totalDebit: 1120000.0,
    totalCredit: 1120000.0,
    preparedBy: 'James Tan, CA',
    approvedBy: 'Sarah Lim, CPA',
    approvedAt: '2026-08-30 15:30 UTC',
    ruleApplied: 'Tokenized Sukuk Purchase via Tokenized Deposit',
    lines: [
      { id: 'jl_3', accountCode: '1220', accountName: 'Tokenized Securities — Khazanah Sovereign Sukuk', debit: 1120000.0, credit: 0, assetSymbol: 'SKUK', quantity: 2000.0, memo: 'Capitalization of 2,000 Sukuk certificates (RM5,000,000 nominal)' },
      { id: 'jl_4', accountCode: '1150', accountName: 'Tokenized Cash & Bank Deposits (CIMB Deposit)', debit: 0, credit: 1120000.0, assetSymbol: 'CIMB-DEP', quantity: 5000000.0, memo: 'Settlement debit from CIMB wholesale tokenized deposit account' },
    ],
    evidenceHash: '3wP8...9kLm',
  },

  // 3. Securitize BUIDL Dividend Distribution Journal
  {
    id: 'je_2026_00842',
    journalNumber: 'JE-2026-00842',
    date: '2026-08-28',
    entityId: 'ent_markets',
    sourceName: 'Securitize BUIDL Platform Feed',
    description: 'Recognition of August 2026 BUIDL Monthly Yield Dividend ($18,450.00)',
    relatedTxId: 'tx_buidl_div_001',
    status: 'READY_FOR_REVIEW',
    totalDebit: 18450.0,
    totalCredit: 18450.0,
    preparedBy: 'James Tan, CA',
    ruleApplied: 'Securitize BUIDL Monthly Dividend Distribution',
    lines: [
      { id: 'jl_5', accountCode: '1100', accountName: 'Cash & Cash Equivalents (USD Settlement Account)', debit: 18450.0, credit: 0, memo: 'Dividend proceeds received in Coinbase clearing account' },
      { id: 'jl_6', accountCode: '4200', accountName: 'Tokenized Fund Dividend & Sukuk Profit Income', debit: 0, credit: 18450.0, memo: 'Operating yield income recognition under IFRS 15' },
    ],
    evidenceHash: 'e71b...0911',
  },
];

export const INITIAL_MONTH_END_TASKS: MonthEndTask[] = [
  {
    id: 'task_data_ingestion',
    name: '1. Ingest & Sync Multi-Venue Feeds',
    title: 'Multi-Venue Data Ingestion & Feed Lock',
    category: 'DATA_INGESTION',
    status: 'COMPLETED',
    owner: 'Alex Chen',
    assignedToName: 'Alex Chen',
    dueDate: '2026-08-31',
    evidenceSummary: 'All venue and issuer-wallet feeds synced (Solana Treasury, Coinbase, Kraken, Securitize, Backed, BlackRock/Khazanah/CIMB Digital Wallets).',
    actionRoute: 'sources',
  },
  {
    id: 'task_cross_reconciliation',
    name: '2. Five-Way Cross-Platform Position Reconciliation',
    title: 'Five-Way Cross-Platform Position Reconciliation',
    category: 'RECONCILIATION',
    status: 'WARNING',
    owner: 'Sarah Lim, CPA',
    assignedToName: 'Sarah Lim, CPA',
    dueDate: '2026-08-31',
    evidenceSummary: '98.2% reconciled. 1 open exception on Backed NVDA (50-unit Kraken ↔ Solana transfer variance).',
    blockingReason: 'Resolve the 50-unit NVIDIA tokenized equity transfer discrepancy to achieve 99.8%+ reconciliation.',
    actionRoute: 'reconciliation',
  },
  {
    id: 'task_tx_classification',
    name: '3. Transaction Normalization & Classification',
    title: 'Transaction Normalization & Classification',
    category: 'CLASSIFICATION',
    status: 'WARNING',
    owner: 'James Tan, CA',
    assignedToName: 'James Tan, CA',
    dueDate: '2026-08-31',
    evidenceSummary: '1 unclassified transaction remaining (Epoch 682 Solana Staking Yield 42.5 SOL).',
    blockingReason: 'Accept suggested classification rule for Epoch 682 staking yield.',
    actionRoute: 'transactions',
  },
  {
    id: 'task_asset_valuation',
    name: '4. Token-to-Underlying Fair Valuation (IFRS 9 / FASB)',
    title: 'Token-to-Underlying Fair Valuation',
    category: 'VALUATION',
    status: 'COMPLETED',
    owner: 'Sarah Lim, CPA',
    assignedToName: 'Sarah Lim, CPA',
    dueDate: '2026-08-31',
    evidenceSummary: 'Level 1 & 2 market prices locked from Securitize ($1.00), BPAM (Sukuk), NASDAQ ($128.50), and Pyth.',
    actionRoute: 'assets',
  },
  {
    id: 'task_subledger_posting',
    name: '5. Controller Maker-Checker Journal Sign-Off',
    title: 'Controller Maker-Checker Journal Sign-Off',
    category: 'JOURNALS',
    status: 'WARNING',
    owner: 'Sarah Lim, CPA',
    assignedToName: 'Sarah Lim, CPA',
    dueDate: '2026-08-31',
    evidenceSummary: '1 pending journal batch awaiting Controller sign-off ($18,450.00 BUIDL dividend).',
    blockingReason: 'Review and approve pending journal batch JE-2026-00842.',
    actionRoute: 'subledger',
  },
  {
    id: 'task_financial_reporting',
    name: '6. Trial Balance & ERP General Ledger Sync',
    title: 'Trial Balance & ERP General Ledger Sync',
    category: 'REPORTING',
    status: 'PENDING',
    owner: 'Sarah Lim, CPA',
    assignedToName: 'Sarah Lim, CPA',
    dueDate: '2026-08-31',
    evidenceSummary: 'Trial Balance balanced with $38.4M tokenized asset control accounts matching SAP General Ledger.',
    actionRoute: 'reports',
  },
  {
    id: 'task_cfo_close_lock',
    name: '7. CFO Period Lock & Audit Trail Verification',
    title: 'CFO Period Lock & Cryptographic Audit Seal',
    category: 'SIGN_OFF',
    status: 'BLOCKED',
    owner: 'David Ross, CFA',
    assignedToName: 'David Ross, CFA',
    dueDate: '2026-08-31',
    evidenceSummary: 'Requires 100% close readiness and resolution of all open reconciliation breaks.',
    blockingReason: 'Blocked until all open reconciliation exceptions and pending journals are authorized.',
    actionRoute: 'close',
  },
];

export const INITIAL_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'audit_001',
    timestamp: '2026-08-31 17:00:00 UTC',
    userId: 'usr_sarah_lim',
    userName: 'Sarah Lim, CPA',
    userRole: 'CONTROLLER',
    action: 'JOURNAL_APPROVED',
    objectType: 'JOURNAL',
    targetType: 'JournalEntry',
    objectId: 'je_2026_00840',
    targetId: 'je_2026_00840',
    newValue: 'POSTED',
    notes: 'Approved internal transfer journal JE-2026-00840 (500k BUIDL from Ethereum to Solana within BlackRock Digital Wallet). Verified no economic disposal.',
    details: 'Verified no economic disposal occurred; internal cross-chain reclassification within the same BNY Mellon-custodied wallet confirmed.',
  },
  {
    id: 'audit_002',
    timestamp: '2026-08-31 17:30:00 UTC',
    userId: 'usr_sarah_lim',
    userName: 'Sarah Lim, CPA',
    userRole: 'CONTROLLER',
    action: 'RECONCILIATION_RESOLVED',
    objectType: 'RECONCILIATION',
    targetType: 'ReconciliationBreakItem',
    objectId: 'rec_break_003',
    targetId: 'rec_break_003',
    newValue: 'RESOLVED',
    notes: 'Verified 5,000,000 units BUIDL across BlackRock Digital Wallet — Solana (3M) and Ethereum (2M), custodied by BNY Mellon, matching Securitize registry attestation.',
  },
  {
    id: 'audit_003',
    timestamp: '2026-08-30 15:30:00 UTC',
    userId: 'usr_sarah_lim',
    userName: 'Sarah Lim, CPA',
    userRole: 'CONTROLLER',
    action: 'JOURNAL_APPROVED',
    objectType: 'JOURNAL',
    targetType: 'JournalEntry',
    objectId: 'je_2026_00841',
    targetId: 'je_2026_00841',
    newValue: 'POSTED',
    notes: 'Approved purchase journal JE-2026-00841 (RM5,000,000 Khazanah Tokenized Sukuk settled via CIMB Tokenized Deposit).',
  },
];
